name: Run Mocha tests and publish Allure report
on: 
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  

      - name: Install dependencies
        run: npm install
        
      - run: npm install mocha allure-mocha
      - run: npm install --global surge

      - run: node runner.js || true
      - run: allure serve allure-results
      - run: allure generate allure-results --clean -o allure-report
      - run: surge allure-report/ jangkau-api.surge.sh --token ${{ secrets.SURGE_TOKEN }}

      # - name: Run Mocha tests
      #   run: npm run regression

      # - name: Load test report history
      #   uses: actions/checkout@v3
      #   if: always()  
      #   continue-on-error: true
      #   with:
      #     ref: gh-pages  
      #     path: gh-pages  

      # - name: Build Allure test report
      #   uses: simple-elf/allure-report-action@v1.7
      #   if: always()
      #   with:
      #     gh_pages: gh-pages 
      #     allure_history: allure-history 
      #     allure_results: allure-results  

      # - name: Publish Allure test report
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: always()
      #   with:
      #     github_token: ${{ secrets.TOKEN }}  
      #     publish_branch: gh-pages  
      #     publish_dir: allure-history  
